### ISSUE TITLE
LRC support?

### ISSUE THREAD

**Issue by Josscii** [dagronf/SwiftSubtitles#12]
LRC is a common format for lyrics, can you support it?

**Comment by dagronf** [comment]
@Josscii 

Hi there, I've just pushed up version 1.8.0 which supports importing Lyrics files (.lrc).  The format is a little undefined but I've tried to make the decoder "fluffy" enough to support some encoded files I could find online.

Can you try it out and see if it works for you?

**Comment by Josscii** [comment]
Thanks for your quick work, I'll check it out and test it!

**Comment by Josscii** [comment]
https://github.com/dagronf/SwiftSubtitles/blob/2009a0be1ea93a531cf40294ae3d3f56d0b53885/Sources/SwiftSubtitles/coding/LRC.swift#L94-L97

Hi, I'm wondering why LRC has this limit?

**Comment by dagronf** [comment]
@Josscii Purely because the format doesn't really define what happens when minutes is > 99.  According to Wikipedia, the time format is `[xx:yy.zz]` where 'xx' is minutes, 'yy' is seconds and 'zz' is hundredths of a second. I don't want to generate files that cannot be read by other apps.  If you can find me a more formal format definition, please do! 

https://en.wikipedia.org/wiki/LRC_(file_format)

**Comment by Josscii** [comment]
@dagronf Got it, thanks for you explanation, I did not find any definition on the web, but I asked ChatGPT, it says the minute > 99 is undefined, so it is safe to limit it here. Great work, really appreciate it! I'll close this issue.
