### ISSUE TITLE
some vtt parse crash

### ISSUE THREAD

**Issue by Josscii** [dagronf/SwiftSubtitles#13]
[英語語音學一.01..Class.Overview.(2020.updated).txt](https://github.com/user-attachments/files/18183629/01.Class.Overview.2020.updated.txt)

**Comment by dagronf** [comment]
Hi @Josscii, sorry you're having issues.

This vtt file is wild.  Loads of empty cues, cues containing only a single space, cues that are duplicated 10ms later, cues that contain only a single space character. Was it automatically generated?

For example :-

```
00:51:49.829 --> 00:51:49.839 align:start position:0%
there are some readings in some of those
 

00:51:49.839 --> 00:51:52.470 align:start position:0%
there are some readings in some of those
languages<00:51:50.400><c> below</c><00:51:50.880><c> i</c><00:51:51.040><c> have</c><00:51:51.200><c> a</c><00:51:51.280><c> couple</c><00:51:51.520><c> of</c><00:51:51.680><c> jokes</c>
```

```
00:00:45.830 --> 00:00:45.840 align:start position:0%
probably more times i saw him once in
 

00:00:45.840 --> 00:00:47.350 align:start position:0%
probably more times i saw him once in
taiwan
```

The issue was that I was trimming lines of whitespace, which would nuke some of the cue entries that contained only a single space (?). The code logic made an assumption regarding the length of an array and as such busted.

Grab the latest build (1.8.2) which should resolve the issue.

Please let me know how you go.

**Comment by Josscii** [comment]
No problem, thank you for your reply.

This file was downloaded from a website, and I’m not sure how the original author generated it. It definitely looks messy.

Thanks for the quick fix, I will test it as soon as possible.

**Comment by Josscii** [comment]
Sorry for the late reply. I can confirm that the fix resolved the crash issue. However, since this file doesn’t seem to be standard, there are some issues with the parsed subtitles. It could be that there’s an issue with the current parsing implementation, or perhaps more fault tolerance is needed.

I tried importing the file into the iOS Files app, and it parsed and worked correctly in the preview. Here’s a screenshot.

https://github.com/user-attachments/assets/021ed628-5761-4bb9-b90e-0372d4787604

```
and<00:00:18.400><c> we'll</c><00:00:18.560><c> go</c><00:00:18.720><c> to</c><00:00:18.880><c> the</c><00:00:18.960><c> web</c><00:00:19.119><c> page</c><00:00:19.359><c> in</c><00:00:19.520><c> a</c><00:00:19.600><c> minute</c>
```
These seems should be ignored.

**Comment by dagronf** [comment]
Hey @Josscii good news on the crash.

If you have concerns with the vtt importer can you raise another issue and close this one? That way the issue doesn't morph away from its original intent.
